apiVersion: v1
kind: Namespace
metadata:
  name: codemonsters
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop

---
apiVersion: v1
kind: Service
metadata:
  namespace: codemonsters
  name: codemonsters
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: website

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: codemonsters
  name: codemonsters
  labels:
    app: codemonsters
spec:
  selector:
    matchLabels:
      app: codemonsters
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: codemonsters
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: codemonsters
          image: maxmorev/codemonsters-website:latest
          ports:
            - containerPort: 80
              name: nginx
          resources:
            requests:
              memory: "16Mi"
              cpu: "150m" # 1/4 core
            limits:
              memory: "128Mi"
              cpu: "250m" # 1/4 core
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1