apiVersion: v1
kind: Namespace
metadata:
  name: codemonsters
  labels:
    app.kubernetes.io/name: codemonsters
    app.kubernetes.io/instance: codemonsters

---
apiVersion: v1
kind: Service
metadata:
  namespace: codemonsters
  name: codemonsters-website
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: codemonsters-website

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: codemonsters
  name: codemonsters-website
  labels:
    app:  codemonsters-website
spec:
  selector:
    matchLabels:
      app: codemonsters-website
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: codemonsters-website
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: codemonsters-website
          image: maxmorev/codemonsters-website:latest
          ports:
            - containerPort: 80
              name: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m" # 1/4 core
            limits:
              memory: "128Mi"
              cpu: "250m" # 1/4 core
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1